Test macports

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -16,9 +16,7 @@ jobs:
       run: |
         v=${version/./}
         export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
-        export TERM=xterm        
-        curl -o pear.phar -SL https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.phar
-        sudo php pear.phar -d /usr/local/lib/php -b /usr/local/bin
+        export TERM=xterm
         curl -o port.pkg -sSL https://github.com/macports/macports-base/releases/download/v2.6.2/MacPorts-2.6.2-10.15-Catalina.pkg
         sudo installer -pkg port.pkg -target /
         sync='false'
@@ -43,15 +41,19 @@ jobs:
         sudo port select --set php php$v
         sudo mkdir -p /usr/local/bin        
         sudo ln -sf /opt/local/bin/* /usr/local/bin
-        sudo rm -rf port.pkg 
-        sudo rm -rf pear.phar
         ini_file=$(php -d "date.timezone=UTC" --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
         sudo chmod 777 "$ini_file"
-        echo "date.timezone=UTC" >>"$ini_file"                              
+        echo "date.timezone=UTC" >>"$ini_file"
+        ext_dir=$(php -i | grep -Ei "extension_dir => /(usr|opt)" | sed -e "s|.*=> s*||")
+        curl -o pear.phar -SL https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.phar
+        sudo php pear.phar -d /opt/local/lib/php$v -b /usr/local/bin || echo 'could not install pear'
         for tool in pear pecl; do
           sudo "$tool" config-set php_ini "$ini_file"          
         done
         pecl config-show
+        echo "ext_dir: $ext_dir"
+        sudo rm -rf port.pkg 
+        sudo rm -rf pear.phar        
       env:
         version: ${{ matrix.php-versions }}
     - name: Test PECL
