Test

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -38,17 +38,18 @@ jobs:
         sudo mkdir -p /usr/local/bin        
         sudo ln -sf /opt/local/bin/* /usr/local/bin
         curl -o pear.phar -SL https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.phar
-        sudo php pear.phar
-        sudo rm -rf port.pkg pear.phar
+        sudo php pear.phar -d /usr/local/lib/php -b /usr/local/bin || echo 'could not install pear'
+        sudo rm -rf port.pkg 
+        sudo rm -rf pear.phar
         ini_file=$(php -d "date.timezone=UTC" --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
-        sudo chmod 777 "$ini_file"
+        sudo chmod 777 "$ini_file" || echo "could not change permissions"
         echo "date.timezone=UTC" >>"$ini_file"
         php_h="https://raw.githubusercontent.com/php/php-src/PHP-$version/main/php.h"
         apiv=$(curl -sSL --retry 5 "$php_h" | grep "PHP_API_VERSION" | cut -d' ' -f 3)
         new_ext_dir="/usr/local/lib/php/pecl/$apiv"
-        sudo mkdir -p $new_ext_dir
-        ext_dir=$(php -i | grep "extension_dir => /opt" | sed -e "s|.*=> s*||")
-        sudo cp -r $ext_dir/* $new_ext_dir
+        sudo mkdir -p $new_ext_dir || echo "could not make ext_dir"
+        ext_dir=$(php -i | grep -Ei "extension_dir => /(opt|usr)" | sed -e "s|.*=> s*||")
+        sudo cp -r "$ext_dir"/* "$new_ext_dir" || echo "could not copy"
         echo "extension_dir=$new_ext_dir" >>"$ini_file"
         for tool in pear pecl; do
           sudo "$tool" config-set php_ini "$ini_file"
