Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,6 +13,8 @@ jobs:
       - name: Test exit 
         run: |
           cross="✗"
-          echo "::error::\033[32;1m$cross \033[0m\033[34;1mPHP \033[0m\033[90;1mPHP $version is not supported on self-hosted runner\033[0m\n"
+          version='5.3'
+          echo "::error::\033[31;1m$cross \033[0m\033[34;1mPHP \033[0m\033[90;1mPHP $version is not supported on self-hosted runner\033[0m\n"
+          exit 1
         
           
