Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,29 +13,21 @@ jobs:
       uses: actions/checkout@v2
 
     - name: check libs
-      run: ls /usr/local/opt
-      
-    - name: check libs
-      run: ls /usr/local/opt/libffi/lib/ || true
+      run: brew update      
   
     - name: setup-php
       uses: shivammathur/setup-php@verbose
       with: 
         php-version: ${{ matrix.php-versions }}
+        extensions: opcache
    
     - name: Test fix 
-      run: |        
-        lib_error=$(php -v 2>&1) || true        
-        libs=$(echo "$lib_error" | grep -m 1 -Eo "(/opt/[a-z]*)" | cut -d '/' -f 3)
-        echo "libs: $libs"
-        for lib in $libs; do
-          #lib_name=$(echo "$lib" | cut -d '.' -f 1)
-          #lib_path=/usr/local/opt/"$lib_name"/lib
-          echo "lib: $lib"
-          #brew install --force https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/$lib.rb
-          brew upgrade --force $lib
-          #sudo cp "$lib_path/$lib_name.dylib" "$lib_path/$lib"
-        done
+      run: |
+        #lib_error=$(php -v 2>&1) || true
+        #libs=$(echo "$lib_error" | grep -m 1 -Eo "(/opt/[a-z]*)" | cut -d '/' -f 3)
+        #for lib in $libs; do
+        #  brew install --force https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/"$lib".rb
+        #done
         php -v
         php -m
     
