Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,15 +7,15 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        operating-system: [macos-latest]
-        php: [8.2, 8.3, 8.4, 8.5, 8.6]
+        operating-system: [ubuntu-latest]
     steps:
-      - name: Setup PHP
-        uses: shivammathur/setup-php@verbose
-        with:
-          php-version: ${{ matrix.php }}
-
-      - name: Check PHP
+      - continue-on-error: true
         run: |
-          php -v
-          php -m
+          error="Release $REF already exists, and it is immutable.\nFor using immutable releases please refer to $link"
+          [[ "${GITHUB_ACTIONS:-}" == "true" ]] && echo "::error::${error//$'\n'/%0A}" || echo "$error"
+      - continue-on-error: true
+        env:
+          GITHUB_ACTIONS: false
+        run: |
+          error="Release $REF already exists, and it is immutable.\nFor using immutable releases please refer to $link"
+          [[ "${GITHUB_ACTIONS:-}" == "true" ]] && echo "::error::${error//$'\n'/%0A}" || echo "$error"
