Fix input and command

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -7,14 +7,14 @@ jobs:
       max-parallel: 6
       matrix:
         operating-system: [windows-latest, ubuntu-latest, macOS-latest]
-        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
+        php-versions: [php5.6, php7.0, php7.1, php7.2, php7.3, php7.4]
     name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
     steps:
       - name: Checkout
         uses: actions/checkout@master
       - name: Check PHP if not windows
         if: matrix.operating-system != 'windows-latest'
-        run: php{{ matrix.php-versions }} -v || echo "Not found"
+        run: {{ matrix.php-versions }} -v || echo "Not found"
       - name: Check PHP if windows
         if: matrix.operating-system == 'windows-latest'
         run: php -v
