Test Xdebug over 2.8.1

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -13,6 +13,30 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v1
+      - name: Install Xdebug 2.8.1
+        env:
+          version: ${{ matrix.php-versions }}
+        run: |
+          switch_version() {
+            for tool in pear pecl php phar phar.phar php-cgi php-config phpize phpdbg; do
+              if [ -e "/usr/bin/$tool$version" ]; then
+                sudo update-alternatives --set $tool /usr/bin/"$tool$version" >/dev/null 2>&1
+              fi
+            done
+          }          
+          find /etc/apt/sources.list.d -type f -name 'ondrej-ubuntu-php*.list' -exec sudo DEBIAN_FRONTEND=noninteractive apt-fast update -o Dir::Etc::sourcelist="{}" ';' >/dev/null 2>&1
+          sudo DEBIAN_FRONTEND=noninteractive apt-fast install -y php"$version" php"$version"-dev php"$version"-xml >/dev/null 2>&1
+          switch_version
+          sudo update-alternatives --set php-config /usr/bin/php-config"$version" >/dev/null 2>&1
+          sudo update-alternatives --set phpize /usr/bin/phpize"$version" >/dev/null 2>&1
+          wget https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.phar >/dev/null 2>&1
+          sudo php install-pear-nozlib.phar >/dev/null 2>&1
+          sudo rm -rf install-pear-nozlib.phar >/dev/null 2>&1
+          ini_file=$(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
+          sudo pear config-set php_ini "$ini_file" >/dev/null 2>&1
+          sudo pear config-set auto_discover 1 >/dev/null 2>&1
+          sudo pear channel-update pear.php.net >/dev/null 2>&1      
+          sudo pecl install xdebug-2.8.1 || echo 'could not install xdebug 2.8.1'
       - name: Install PHP
         uses: shivammathur/setup-php@develop
         with:
