Test Xdebug on PHP 8

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -7,45 +7,23 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        operating-system: [ubuntu-latest, ubuntu-16.04, macOS-latest]
+        operating-system: [ubuntu-latest, ubuntu-16.04, macos-latest]
         php-versions: ['8.0']
     steps:
       - name: Checkout
-        uses: actions/checkout@v1
-        with:
-          fetch-depth: 1
+        uses: actions/checkout@v2
 
-      - name: Setup PHP with extensions and custom config
+      - name: Setup PHP
         uses: shivammathur/setup-php@develop
         env:
           php-version: ${{ matrix.php-versions }}
-          extension-csv: mbstring, xdebug, pcov #optional
-          ini-values-csv: post_max_size=256M, short_open_tag=On, date.timezone=Asia/Kolkata #optional
-
+          
+      - name: Install Xdebug
+        run: |
+          cd ~ && git clone --depth=1 https://github.com/xdebug/xdebug.git
+          cd xdebug || echo "Failed to clone Xdebug"
+          sudo ./rebuild.sh
+          
       - name: Testing PHP version
         run: |
           php -v
-          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
-
-      - name: Testing Composer version
-        run: |
-          composer -V
-          php -r "if(strpos(@exec('composer -V'), 'Composer version') === false) {throw new Exception('Composer not found');}"
-      - name: Testing Extensions
-        run: |
-          php -m
-          php -r "if(! extension_loaded('mbstring')) {throw new Exception('mbstring not found');}"
-          # php -r "if(! extension_loaded('Xdebug')) {throw new Exception('Xdebug not found');}"
-          php -r "if(! extension_loaded('pcov')) {throw new Exception('PCOV not found');}"
-      - name: Testing ini values
-        run: |
-          php -r "if(ini_get('post_max_size')!='256M') {throw new Exception('post_max_size not added');}"
-          php -r "if(ini_get('short_open_tag')!=1) {throw new Exception('short_open_tag not added');}"
-          php -r "if(ini_get('date.timezone')!='Asia/Kolkata') {throw new Exception('date.timezone not added');}"
-      - name: Test and Benchmark JIT
-        run: |
-          php -r "if(! extension_loaded('Zend OPcache')) {throw new Exception('Zend OPcache not found');}"
-          php -r "if(ini_get('opcache.jit_buffer_size')!='256M') {throw new Exception('opcache.jit_buffer_size not set');}"
-          php -r "if(ini_get('opcache.jit')!=1235) {throw new Exception('opcache.jit not set');}"
-          php -r "if(ini_get('pcre.jit')!=1) {throw new Exception('pcre.jit not set');}"
-          curl https://raw.githubusercontent.com/php/php-src/master/Zend/bench.php | php
